language:
  - elixir

elixir:
  - 1.5.1

otp_release:
  - 19.2
  - 20.0

sudo: false

cache:
  directories:
    - .dialyzer

script:
  - mix test
  - mix property
  - mix dialyzer
  - mix credo --strict
